<?php
// +----------------------------------------------------------------------
// | [RhaPHP System] Copyright (c) 2017 http://www.rhaphp.com/
// +----------------------------------------------------------------------
// | [RhaPHP] 并不是自由软件,你可免费使用,未经许可不能去掉RhaPHP相关版权
// +----------------------------------------------------------------------
// | Author: Geeson <qimengkeji@vip.qq.com>
// +----------------------------------------------------------------------


namespace app\store\controller;


use app\common\model\Addons;
use think\Db;
use think\Exception;
use think\facade\Request;
use think\facade\Session;
use think\facade\Url;
use think\Validate;

class Index extends Base
{

    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function list()
    {
        $MpList = Db::name('store_list')
            ->where(['uid' => $this->admin_id])
            ->select();
        foreach ($MpList as $key => $v) {
            $MpList[$key]['type'] = getMpType($v['type']);
        }
        $this->assign('menu_title', '店铺管理');
        $this->assign('storeList', $MpList);
        return view();
    }

    public function checkStoreParams($data){
            if (utf8_strlen($data['name']) > 10) {
                return '名字太长';
            }

            if (utf8_strlen($data['address']) > 60) {
                return '地址太长';
            }
        
            if (strlen($data['logo']) > 200) {
                return 'logo字符不能超过200';
            }
            
            return true;
    
    }

    public function addStore(){
        if (Request::isAjax() && Request::isPost()) {
            $data = input('post.');
            
            $checkMsg = $this->checkStoreParams($data);
            if ($checkMsg !== TRUE) {
                return ajaxMsg(0, $checkMsg);
            } 

            $mode = new \app\common\model\StoreList();
            $id = $mode->insertGetId(
                [
                'name' => $data['name'], 
                'address' => $data['address'], 
                'logo' => $data['logo'], 
                'type' => (int)$data['type'], 
                'uid' => $this->admin_id
                ]);
            if ($id) {
                ajaxMsg(1, '新增成功');
            }
            ajaxMsg(0, '新增失败');
        }
        $this->assign('menu_title', '新增店铺');
        return  view('addStore');
    }

    public function editStore(){
        $mode = new \app\common\model\StoreList();
        if (Request::isAjax() && Request::isPost()) {
            $data = input('post.');
            
            $checkMsg = $this->checkStoreParams($data);
            if ($checkMsg !== TRUE) {
                return ajaxMsg(0, $checkMsg);
            } 

            $aUpdate = [
                'name' => $data['name'], 
                'address' => $data['address'], 
                'type' => (int)$data['type'], 
                ];
            if ($data['logo'] != '') {
                $aUpdate['logo'] = $data['logo'];
            }

            $res = $mode->allowField(true)->save($aUpdate, ['id' => (int)$data['id'], 'uid' => $this->admin_id]);
            if ($res) {
                return ajaxMsg(0, '更新成功');
            }
            return ajaxMsg(0, '更新失败');
        }
        $id = (int)input('id');
        $aStore = Db::name('store_list')->where(['id'=>$id, 'uid'=>$this->admin_id])->select();
        if (count($aStore) <= 0) {
            $this->assign('menu_title', '新增店铺');
            view('addStore');
        }
        
        $this->assign('data', $aStore[0]);
        $this->assign('menu_title', '修改店铺');
        return  view('editStore');
    }


}
